---
services:
  main:
    command: /start-aa.sh
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - HTTP_PORT=${HTTP_PORT}
      - HTTPS_PORT=${HTTPS_PORT}
    image: registry.camunda.cloud/team-cambpm/automationanywhere:A2019-8098-V2
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
      - ${HTTPS_PORT}:${HTTPS_PORT}
    restart: on-failure
version: '3'
