services:
  main:
    deploy:
      restart_policy:
        condition: on-failure
    environment: []
    image: gcr.io/ci-30-162810/cockroachdb:20.1v0.1.3
    ports:
      - 26257/tcp
      - 8080/tcp
    restart: on-failure
version: '3'
